version: '3'
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile.dev
        tty: true
        command: bash
        environment:
            PYTHONIOENCODING: utf-8
            PYTHONPATH: /work
            NOSE_NOCAPTURE: 1
        ports:
            - "3000:3000"
        volumes:
            - "./:/work"
        # entrypoint: python /work/server.py
        # entrypoint: /work/coverage_test.sh

    postgres:
        image: postgres:10.5
        environment:
            POSTGRES_DB: authz
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        # volumes:
        #     - "./pg-data:/var/lib/postgresql"
